/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Role = IDL.Variant({
  'Directed' : IDL.Null,
  'Produced' : IDL.Null,
  'Assisted' : IDL.Null,
});
export const ContactFormSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'role' : Role,
  'year' : IDL.Nat,
  'logline' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'addProject' : IDL.Func(
      [IDL.Text, Role, IDL.Nat, IDL.Opt(IDL.Text), IDL.Bool],
      [],
      [],
    ),
  'deleteProject' : IDL.Func([IDL.Nat], [], []),
  'getAllContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactFormSubmission)],
      ['query'],
    ),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getFeaturedProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getProjectsByYear' : IDL.Func([IDL.Nat], [IDL.Vec(Project)], ['query']),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateProject' : IDL.Func(
      [IDL.Nat, IDL.Text, Role, IDL.Nat, IDL.Opt(IDL.Text), IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Role = IDL.Variant({
    'Directed' : IDL.Null,
    'Produced' : IDL.Null,
    'Assisted' : IDL.Null,
  });
  const ContactFormSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'role' : Role,
    'year' : IDL.Nat,
    'logline' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'addProject' : IDL.Func(
        [IDL.Text, Role, IDL.Nat, IDL.Opt(IDL.Text), IDL.Bool],
        [],
        [],
      ),
    'deleteProject' : IDL.Func([IDL.Nat], [], []),
    'getAllContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactFormSubmission)],
        ['query'],
      ),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getFeaturedProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getProjectsByYear' : IDL.Func([IDL.Nat], [IDL.Vec(Project)], ['query']),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateProject' : IDL.Func(
        [IDL.Nat, IDL.Text, Role, IDL.Nat, IDL.Opt(IDL.Text), IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };